module Test.TestCases (prettyTestReference) where

import Language.Haskell.Exts.Annotated
import Data.List (find)

prettyTestReference :: PPLayout -> String -> Maybe (Module SrcSpanInfo)
prettyTestReference layout fileName = find (\x -> fileName == takeFileName x) $ testCases layout
  where
    takeFileName x = srcSpanFilename . srcInfoSpan $ ann x
    testCases :: PPLayout -> [Module SrcSpanInfo]
    testCases PPOffsideRule = offsideRule
    testCases PPSemiColon   = semiColonRule
    testCases PPInLine      = inlineRule
    testCases _             = noLayoutRule

offsideRule   = [
    Module (SrcSpanInfo (SrcSpan "WithKeyword.hs" 1 1 2 1) [SrcSpan "WithKeyword.hs" 1 1 1 1, SrcSpan "WithKeyword.hs" 1 1 1 1, SrcSpan "WithKeyword.hs" 1 1 1 1, SrcSpan "WithKeyword.hs" 1 1 1 1, SrcSpan "WithKeyword.hs" 2 1 2 1]) Nothing [] [] [PatBind (SrcSpanInfo (SrcSpan "WithKeyword.hs" 1 1 1 9) []) (PVar (SrcSpanInfo (SrcSpan "WithKeyword.hs" 1 1 1 5) []) (Ident (SrcSpanInfo (SrcSpan "WithKeyword.hs" 1 1 1 5) []) "with")) Nothing (UnGuardedRhs (SrcSpanInfo (SrcSpan "WithKeyword.hs" 1 6 1 9) [SrcSpan "WithKeyword.hs" 1 6 1 7]) (Lit (SrcSpanInfo (SrcSpan "WithKeyword.hs" 1 8 1 9) []) (Int (SrcSpanInfo (SrcSpan "WithKeyword.hs" 1 8 1 9) []) 1 "1"))) Nothing]
   ,Module (SrcSpanInfo (SrcSpan "Ex1.hs" 1 1 3 1) [SrcSpan "Ex1.hs" 1 1 1 1, SrcSpan "Ex1.hs" 1 1 1 1, SrcSpan "Ex1.hs" 1 1 1 1, SrcSpan "Ex1.hs" 1 1 1 1, SrcSpan "Ex1.hs" 3 1 3 1]) Nothing [] [] [PatBind (SrcSpanInfo (SrcSpan "Ex1.hs" 1 1 2 14) [SrcSpan "Ex1.hs" 2 3 2 8]) (PVar (SrcSpanInfo (SrcSpan "Ex1.hs" 1 1 1 4) []) (Ident (SrcSpanInfo (SrcSpan "Ex1.hs" 1 1 1 4) []) "yes")) Nothing (UnGuardedRhs (SrcSpanInfo (SrcSpan "Ex1.hs" 1 5 1 8) [SrcSpan "Ex1.hs" 1 5 1 6]) (Lit (SrcSpanInfo (SrcSpan "Ex1.hs" 1 7 1 8) []) (Int (SrcSpanInfo (SrcSpan "Ex1.hs" 1 7 1 8) []) 1 "1"))) (Just (BDecls (SrcSpanInfo (SrcSpan "Ex1.hs" 2 9 2 14) [SrcSpan "Ex1.hs" 2 9 2 9, SrcSpan "Ex1.hs" 2 14 2 14]) [PatBind (SrcSpanInfo (SrcSpan "Ex1.hs" 2 9 2 14) []) (PVar (SrcSpanInfo (SrcSpan "Ex1.hs" 2 9 2 10) []) (Ident (SrcSpanInfo (SrcSpan "Ex1.hs" 2 9 2 10) []) "x")) Nothing (UnGuardedRhs (SrcSpanInfo (SrcSpan "Ex1.hs" 2 11 2 14) [SrcSpan "Ex1.hs" 2 11 2 12]) (Lit (SrcSpanInfo (SrcSpan "Ex1.hs" 2 13 2 14) []) (Int (SrcSpanInfo (SrcSpan "Ex1.hs" 2 13 2 14) []) 1 "1"))) Nothing]))]
   ,Module (SrcSpanInfo (SrcSpan "SimpleDeriving.hs" 1 1 4 1) [SrcSpan "SimpleDeriving.hs" 1 1 1 1, SrcSpan "SimpleDeriving.hs" 1 1 1 1, SrcSpan "SimpleDeriving.hs" 1 1 1 1, SrcSpan "SimpleDeriving.hs" 1 1 1 1, SrcSpan "SimpleDeriving.hs" 4 1 4 1]) Nothing [] [] [DataDecl (SrcSpanInfo (SrcSpan "SimpleDeriving.hs" 2 1 3 16) [SrcSpan "SimpleDeriving.hs" 2 8 2 9]) (DataType (SrcSpanInfo (SrcSpan "SimpleDeriving.hs" 2 1 2 5) [])) Nothing (DHead (SrcSpanInfo (SrcSpan "SimpleDeriving.hs" 2 6 2 7) []) (Ident (SrcSpanInfo (SrcSpan "SimpleDeriving.hs" 2 6 2 7) []) "T") []) [QualConDecl (SrcSpanInfo (SrcSpan "SimpleDeriving.hs" 2 10 2 11) []) Nothing Nothing (ConDecl (SrcSpanInfo (SrcSpan "SimpleDeriving.hs" 2 10 2 11) []) (Ident (SrcSpanInfo (SrcSpan "SimpleDeriving.hs" 2 10 2 11) []) "T") [])] (Just (Deriving (SrcSpanInfo (SrcSpan "SimpleDeriving.hs" 3 5 3 16) [SrcSpan "SimpleDeriving.hs" 3 5 3 13]) [IHead (SrcSpanInfo (SrcSpan "SimpleDeriving.hs" 3 14 3 16) []) (UnQual (SrcSpanInfo (SrcSpan "SimpleDeriving.hs" 3 14 3 16) []) (Ident (SrcSpanInfo (SrcSpan "SimpleDeriving.hs" 3 14 3 16) []) "Eq")) []]))]
  ]
semiColonRule = [
   Module (SrcSpanInfo (SrcSpan "WithKeyword.hs" 1 1 2 1) [SrcSpan "WithKeyword.hs" 1 1 1 1, SrcSpan "WithKeyword.hs" 1 1 1 1, SrcSpan "WithKeyword.hs" 1 1 1 1, SrcSpan "WithKeyword.hs" 1 1 1 1, SrcSpan "WithKeyword.hs" 2 1 2 1]) Nothing [] [] [PatBind (SrcSpanInfo (SrcSpan "WithKeyword.hs" 1 1 1 9) []) (PVar (SrcSpanInfo (SrcSpan "WithKeyword.hs" 1 1 1 5) []) (Ident (SrcSpanInfo (SrcSpan "WithKeyword.hs" 1 1 1 5) []) "with")) Nothing (UnGuardedRhs (SrcSpanInfo (SrcSpan "WithKeyword.hs" 1 6 1 9) [SrcSpan "WithKeyword.hs" 1 6 1 7]) (Lit (SrcSpanInfo (SrcSpan "WithKeyword.hs" 1 8 1 9) []) (Int (SrcSpanInfo (SrcSpan "WithKeyword.hs" 1 8 1 9) []) 1 "1"))) Nothing]
  ,Module (SrcSpanInfo (SrcSpan "Ex1.hs" 1 1 3 1) [SrcSpan "Ex1.hs" 1 1 1 1, SrcSpan "Ex1.hs" 1 1 1 1, SrcSpan "Ex1.hs" 1 1 1 1, SrcSpan "Ex1.hs" 1 1 1 1, SrcSpan "Ex1.hs" 3 1 3 1]) Nothing [] [] [PatBind (SrcSpanInfo (SrcSpan "Ex1.hs" 1 1 2 18) [SrcSpan "Ex1.hs" 2 3 2 8]) (PVar (SrcSpanInfo (SrcSpan "Ex1.hs" 1 1 1 4) []) (Ident (SrcSpanInfo (SrcSpan "Ex1.hs" 1 1 1 4) []) "yes")) Nothing (UnGuardedRhs (SrcSpanInfo (SrcSpan "Ex1.hs" 1 5 1 8) [SrcSpan "Ex1.hs" 1 5 1 6]) (Lit (SrcSpanInfo (SrcSpan "Ex1.hs" 1 7 1 8) []) (Int (SrcSpanInfo (SrcSpan "Ex1.hs" 1 7 1 8) []) 1 "1"))) (Just (BDecls (SrcSpanInfo (SrcSpan "Ex1.hs" 2 9 2 18) [SrcSpan "Ex1.hs" 2 9 2 10, SrcSpan "Ex1.hs" 2 17 2 18]) [PatBind (SrcSpanInfo (SrcSpan "Ex1.hs" 2 11 2 16) []) (PVar (SrcSpanInfo (SrcSpan "Ex1.hs" 2 11 2 12) []) (Ident (SrcSpanInfo (SrcSpan "Ex1.hs" 2 11 2 12) []) "x")) Nothing (UnGuardedRhs (SrcSpanInfo (SrcSpan "Ex1.hs" 2 13 2 16) [SrcSpan "Ex1.hs" 2 13 2 14]) (Lit (SrcSpanInfo (SrcSpan "Ex1.hs" 2 15 2 16) []) (Int (SrcSpanInfo (SrcSpan "Ex1.hs" 2 15 2 16) []) 1 "1"))) Nothing]))]
  ,Module (SrcSpanInfo (SrcSpan "SimpleDeriving.hs" 1 1 4 1) [SrcSpan "SimpleDeriving.hs" 1 1 1 1, SrcSpan "SimpleDeriving.hs" 1 1 1 1, SrcSpan "SimpleDeriving.hs" 1 1 1 1, SrcSpan "SimpleDeriving.hs" 1 1 1 1, SrcSpan "SimpleDeriving.hs" 4 1 4 1]) Nothing [] [] [DataDecl (SrcSpanInfo (SrcSpan "SimpleDeriving.hs" 2 1 3 16) [SrcSpan "SimpleDeriving.hs" 2 8 2 9]) (DataType (SrcSpanInfo (SrcSpan "SimpleDeriving.hs" 2 1 2 5) [])) Nothing (DHead (SrcSpanInfo (SrcSpan "SimpleDeriving.hs" 2 6 2 7) []) (Ident (SrcSpanInfo (SrcSpan "SimpleDeriving.hs" 2 6 2 7) []) "T") []) [QualConDecl (SrcSpanInfo (SrcSpan "SimpleDeriving.hs" 2 10 2 11) []) Nothing Nothing (ConDecl (SrcSpanInfo (SrcSpan "SimpleDeriving.hs" 2 10 2 11) []) (Ident (SrcSpanInfo (SrcSpan "SimpleDeriving.hs" 2 10 2 11) []) "T") [])] (Just (Deriving (SrcSpanInfo (SrcSpan "SimpleDeriving.hs" 3 5 3 16) [SrcSpan "SimpleDeriving.hs" 3 5 3 13]) [IHead (SrcSpanInfo (SrcSpan "SimpleDeriving.hs" 3 14 3 16) []) (UnQual (SrcSpanInfo (SrcSpan "SimpleDeriving.hs" 3 14 3 16) []) (Ident (SrcSpanInfo (SrcSpan "SimpleDeriving.hs" 3 14 3 16) []) "Eq")) []]))]
  ]
inlineRule = [
   Module (SrcSpanInfo (SrcSpan "WithKeyword.hs" 1 1 1 10) [SrcSpan "WithKeyword.hs" 1 1 1 1, SrcSpan "WithKeyword.hs" 1 1 1 1, SrcSpan "WithKeyword.hs" 1 1 1 1, SrcSpan "WithKeyword.hs" 1 1 1 1, SrcSpan "WithKeyword.hs" 1 10 1 10]) Nothing [] [] [PatBind (SrcSpanInfo (SrcSpan "WithKeyword.hs" 1 1 1 9) []) (PVar (SrcSpanInfo (SrcSpan "WithKeyword.hs" 1 1 1 5) []) (Ident (SrcSpanInfo (SrcSpan "WithKeyword.hs" 1 1 1 5) []) "with")) Nothing (UnGuardedRhs (SrcSpanInfo (SrcSpan "WithKeyword.hs" 1 6 1 9) [SrcSpan "WithKeyword.hs" 1 6 1 7]) (Lit (SrcSpanInfo (SrcSpan "WithKeyword.hs" 1 8 1 9) []) (Int (SrcSpanInfo (SrcSpan "WithKeyword.hs" 1 8 1 9) []) 1 "1"))) Nothing]
  ,Module (SrcSpanInfo (SrcSpan "Ex1.hs" 1 1 1 25) [SrcSpan "Ex1.hs" 1 1 1 1, SrcSpan "Ex1.hs" 1 1 1 1, SrcSpan "Ex1.hs" 1 1 1 1, SrcSpan "Ex1.hs" 1 1 1 1, SrcSpan "Ex1.hs" 1 25 1 25]) Nothing [] [] [PatBind (SrcSpanInfo (SrcSpan "Ex1.hs" 1 1 1 24) [SrcSpan "Ex1.hs" 1 9 1 14]) (PVar (SrcSpanInfo (SrcSpan "Ex1.hs" 1 1 1 4) []) (Ident (SrcSpanInfo (SrcSpan "Ex1.hs" 1 1 1 4) []) "yes")) Nothing (UnGuardedRhs (SrcSpanInfo (SrcSpan "Ex1.hs" 1 5 1 8) [SrcSpan "Ex1.hs" 1 5 1 6]) (Lit (SrcSpanInfo (SrcSpan "Ex1.hs" 1 7 1 8) []) (Int (SrcSpanInfo (SrcSpan "Ex1.hs" 1 7 1 8) []) 1 "1"))) (Just (BDecls (SrcSpanInfo (SrcSpan "Ex1.hs" 1 15 1 24) [SrcSpan "Ex1.hs" 1 15 1 16, SrcSpan "Ex1.hs" 1 23 1 24]) [PatBind (SrcSpanInfo (SrcSpan "Ex1.hs" 1 17 1 22) []) (PVar (SrcSpanInfo (SrcSpan "Ex1.hs" 1 17 1 18) []) (Ident (SrcSpanInfo (SrcSpan "Ex1.hs" 1 17 1 18) []) "x")) Nothing (UnGuardedRhs (SrcSpanInfo (SrcSpan "Ex1.hs" 1 19 1 22) [SrcSpan "Ex1.hs" 1 19 1 20]) (Lit (SrcSpanInfo (SrcSpan "Ex1.hs" 1 21 1 22) []) (Int (SrcSpanInfo (SrcSpan "Ex1.hs" 1 21 1 22) []) 1 "1"))) Nothing]))]
  ,Module (SrcSpanInfo (SrcSpan "SimpleDeriving.hs" 1 1 2 24) [SrcSpan "SimpleDeriving.hs" 1 1 1 1, SrcSpan "SimpleDeriving.hs" 1 1 1 1, SrcSpan "SimpleDeriving.hs" 1 1 1 1, SrcSpan "SimpleDeriving.hs" 1 1 1 1, SrcSpan "SimpleDeriving.hs" 2 24 2 24]) Nothing [] [] [DataDecl (SrcSpanInfo (SrcSpan "SimpleDeriving.hs" 2 1 2 23) [SrcSpan "SimpleDeriving.hs" 2 8 2 9]) (DataType (SrcSpanInfo (SrcSpan "SimpleDeriving.hs" 2 1 2 5) [])) Nothing (DHead (SrcSpanInfo (SrcSpan "SimpleDeriving.hs" 2 6 2 7) []) (Ident (SrcSpanInfo (SrcSpan "SimpleDeriving.hs" 2 6 2 7) []) "T") []) [QualConDecl (SrcSpanInfo (SrcSpan "SimpleDeriving.hs" 2 10 2 11) []) Nothing Nothing (ConDecl (SrcSpanInfo (SrcSpan "SimpleDeriving.hs" 2 10 2 11) []) (Ident (SrcSpanInfo (SrcSpan "SimpleDeriving.hs" 2 10 2 11) []) "T") [])] (Just (Deriving (SrcSpanInfo (SrcSpan "SimpleDeriving.hs" 2 12 2 23) [SrcSpan "SimpleDeriving.hs" 2 12 2 20]) [IHead (SrcSpanInfo (SrcSpan "SimpleDeriving.hs" 2 21 2 23) []) (UnQual (SrcSpanInfo (SrcSpan "SimpleDeriving.hs" 2 21 2 23) []) (Ident (SrcSpanInfo (SrcSpan "SimpleDeriving.hs" 2 21 2 23) []) "Eq")) []]))]
  ]
noLayoutRule = [
   Module (SrcSpanInfo (SrcSpan "WithKeyword.hs" 1 1 1 10) [SrcSpan "WithKeyword.hs" 1 1 1 1, SrcSpan "WithKeyword.hs" 1 1 1 1, SrcSpan "WithKeyword.hs" 1 1 1 1, SrcSpan "WithKeyword.hs" 1 1 1 1, SrcSpan "WithKeyword.hs" 1 10 1 10]) Nothing [] [] [PatBind (SrcSpanInfo (SrcSpan "WithKeyword.hs" 1 1 1 9) []) (PVar (SrcSpanInfo (SrcSpan "WithKeyword.hs" 1 1 1 5) []) (Ident (SrcSpanInfo (SrcSpan "WithKeyword.hs" 1 1 1 5) []) "with")) Nothing (UnGuardedRhs (SrcSpanInfo (SrcSpan "WithKeyword.hs" 1 6 1 9) [SrcSpan "WithKeyword.hs" 1 6 1 7]) (Lit (SrcSpanInfo (SrcSpan "WithKeyword.hs" 1 8 1 9) []) (Int (SrcSpanInfo (SrcSpan "WithKeyword.hs" 1 8 1 9) []) 1 "1"))) Nothing]
  ,Module (SrcSpanInfo (SrcSpan "Ex1.hs" 1 1 1 25) [SrcSpan "Ex1.hs" 1 1 1 1, SrcSpan "Ex1.hs" 1 1 1 1, SrcSpan "Ex1.hs" 1 1 1 1, SrcSpan "Ex1.hs" 1 1 1 1, SrcSpan "Ex1.hs" 1 25 1 25]) Nothing [] [] [PatBind (SrcSpanInfo (SrcSpan "Ex1.hs" 1 1 1 24) [SrcSpan "Ex1.hs" 1 9 1 14]) (PVar (SrcSpanInfo (SrcSpan "Ex1.hs" 1 1 1 4) []) (Ident (SrcSpanInfo (SrcSpan "Ex1.hs" 1 1 1 4) []) "yes")) Nothing (UnGuardedRhs (SrcSpanInfo (SrcSpan "Ex1.hs" 1 5 1 8) [SrcSpan "Ex1.hs" 1 5 1 6]) (Lit (SrcSpanInfo (SrcSpan "Ex1.hs" 1 7 1 8) []) (Int (SrcSpanInfo (SrcSpan "Ex1.hs" 1 7 1 8) []) 1 "1"))) (Just (BDecls (SrcSpanInfo (SrcSpan "Ex1.hs" 1 15 1 24) [SrcSpan "Ex1.hs" 1 15 1 16, SrcSpan "Ex1.hs" 1 23 1 24]) [PatBind (SrcSpanInfo (SrcSpan "Ex1.hs" 1 17 1 22) []) (PVar (SrcSpanInfo (SrcSpan "Ex1.hs" 1 17 1 18) []) (Ident (SrcSpanInfo (SrcSpan "Ex1.hs" 1 17 1 18) []) "x")) Nothing (UnGuardedRhs (SrcSpanInfo (SrcSpan "Ex1.hs" 1 19 1 22) [SrcSpan "Ex1.hs" 1 19 1 20]) (Lit (SrcSpanInfo (SrcSpan "Ex1.hs" 1 21 1 22) []) (Int (SrcSpanInfo (SrcSpan "Ex1.hs" 1 21 1 22) []) 1 "1"))) Nothing]))]
  ,Module (SrcSpanInfo (SrcSpan "SimpleDeriving.hs" 1 1 1 24) [SrcSpan "SimpleDeriving.hs" 1 1 1 1, SrcSpan "SimpleDeriving.hs" 1 1 1 1, SrcSpan "SimpleDeriving.hs" 1 1 1 1, SrcSpan "SimpleDeriving.hs" 1 1 1 1, SrcSpan "SimpleDeriving.hs" 1 24 1 24]) Nothing [] [] [DataDecl (SrcSpanInfo (SrcSpan "SimpleDeriving.hs" 1 1 1 23) [SrcSpan "SimpleDeriving.hs" 1 8 1 9]) (DataType (SrcSpanInfo (SrcSpan "SimpleDeriving.hs" 1 1 1 5) [])) Nothing (DHead (SrcSpanInfo (SrcSpan "SimpleDeriving.hs" 1 6 1 7) []) (Ident (SrcSpanInfo (SrcSpan "SimpleDeriving.hs" 1 6 1 7) []) "T") []) [QualConDecl (SrcSpanInfo (SrcSpan "SimpleDeriving.hs" 1 10 1 11) []) Nothing Nothing (ConDecl (SrcSpanInfo (SrcSpan "SimpleDeriving.hs" 1 10 1 11) []) (Ident (SrcSpanInfo (SrcSpan "SimpleDeriving.hs" 1 10 1 11) []) "T") [])] (Just (Deriving (SrcSpanInfo (SrcSpan "SimpleDeriving.hs" 1 12 1 23) [SrcSpan "SimpleDeriving.hs" 1 12 1 20]) [IHead (SrcSpanInfo (SrcSpan "SimpleDeriving.hs" 1 21 1 23) []) (UnQual (SrcSpanInfo (SrcSpan "SimpleDeriving.hs" 1 21 1 23) []) (Ident (SrcSpanInfo (SrcSpan "SimpleDeriving.hs" 1 21 1 23) []) "Eq")) []]))]
  ]
